name: jest

on:
  - push

jobs:
  test:
    name: jest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - run: yarn install

      - run: yarn test --coverage

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
